export const LANGUAGES = ['en', 'vi'] as const;
export type Language = (typeof LANGUAGES)[number];

export const DEFAULT_LANGUAGE: Language = 'en';
export const LANGUAGE_STORAGE_KEY = 'human-atlas.language';

const englishMessages = {
  'language.label': 'Language',
  'language.english': 'English',
  'language.vietnamese': 'Tiếng Việt',
  'brand.name': 'Human Atlas',
  'brand.interactiveAnatomy': 'Interactive anatomy',
  'identity.modeledPieces': '{count} modeled pieces',
  'identity.source': 'BodyParts3D',
  'navigation.explorerPanels': 'Explorer panels',
  'controls.search': 'Find a structure',
  'controls.searchAria': 'Search anatomy',
  'controls.about': 'About this atlas',
  'controls.closePanel': 'Close panel',
  'controls.systems': 'Systems',
  'controls.closeSystems': 'Close systems',
  'controls.all': 'All',
  'controls.skeleton': 'Skeleton',
  'controls.organs': 'Organs',
  'controls.hideAll': 'Hide all',
  'controls.reset': 'Reset',
  'controls.resetViewLayers': 'Reset view and layers',
  'controls.explode': 'Explode anatomy',
  'controls.assembled': 'Assembled',
  'controls.everyPiece': 'Every piece',
  'controls.openSystems': 'Open system layers',
  'controls.sourceCredits': 'Source & credits',
  'controls.showOnlySystem': 'Show only this system',
  'controls.toggleSystem': 'Show or hide this system',
  'controls.piecesVisible': '{count} pieces visible',
  'search.close': 'Close search',
  'search.dismiss': 'Dismiss search suggestions',
  'search.placeholder': 'Search a structure by name or ID…',
  'search.aria': 'Search named anatomical structures',
  'search.noMatches': 'No structures match your search.',
  'search.emptyHint': 'Start with a major organ, or search every named structure.',
  'search.refineHint': 'Showing up to 80 matches. Refine your search to find smaller structures.',
  'search.piece': 'piece',
  'search.pieces': 'pieces',
  'loading.preparing': 'Preparing the anatomy',
  'loading.progress': '{progress}% · Loading {count} pieces',
  'controls.reload': 'Reload viewer',
  'camera.controls': 'Camera controls',
  'camera.threeQuarter': 'Three-quarter view',
  'camera.front': 'Front view',
  'camera.side': 'Side view',
  'camera.back': 'Back view',
  'camera.rotate': 'Rotate body',
  'camera.pause': 'Pause rotation',
  'camera.autoRotate': 'Auto rotate',
  'camera.dragOrbit': 'Drag to orbit',
  'camera.dragPan': 'Drag to pan',
  'camera.pinchZoom': 'Pinch to zoom',
  'camera.tapInspect': 'Tap to inspect',
  'scene.aria': 'Interactive human anatomy. Drag to orbit, pinch or scroll to zoom, and tap a structure to inspect it.',
  'scene.selectedStructure': 'Selected structure',
  'scene.inventory': 'Anatomical inventory',
  'scene.separatedStructures': 'Separated structures',
  'scene.adultMale': 'ADULT HUMAN · MALE',
  'evidence.verified': 'Verified',
  'evidence.provisionalSourced': 'Not fully verified',
  'evidence.provisionalTranslated': 'Source not identified',
  'evidence.noTranslation': 'English only',
  'evidence.direct.label': 'Source verified',
  'evidence.direct.description': 'Term checked against specialist references.',
  'evidence.multiAuthority.description': '{count} independent sources record this term.',
  'evidence.derived.label': 'Derived from verified terminology',
  'evidence.derived.description': 'Term formed using consistent rules from sourced components; the full phrase may not appear verbatim in a source.',
  'evidence.sourced.label': 'Reference source available',
  'evidence.sourced.qualifier': 'Not fully verified',
  'evidence.sourced.description': 'A reference term exists, but scope or usage still differs.',
  'evidence.generated.label': 'Temporary translation',
  'evidence.generated.qualifier': 'Source not identified',
  'evidence.generated.description': 'Translation provided to support Vietnamese use; no confirmed terminology source has been identified.',
  'evidence.conflict.label': 'Source variants',
  'evidence.conflict.description': 'Reference materials use different names.',
  'evidence.noTranslation.label': 'Vietnamese term unavailable',
  'evidence.noTranslation.description': 'No Vietnamese term is available in the terminology record.',
  'evidence.sourceHeading': 'Sources',
  'evidence.showSourceDetails': 'View source details',
  'evidence.sourceUnavailable': 'Reference source details are unavailable.',
  'evidence.openSource': 'Open reference source',
  'evidence.moreSources': '+{count} sources',
  'evidence.fullTitle': 'Full title',
  'evidence.institution': 'Institution',
  'evidence.authors': 'Author(s)',
  'evidence.year': 'Year',
  'evidence.edition': 'Edition',
  'evidence.publisher': 'Publisher',
  'evidence.locator': 'Locator',
  'evidence.page': 'Page {page}',
  'evidence.section': 'Section {section}',
  'evidence.moreLocators': '+{count} more locations',
  'evidence.sourceVariants': 'Observed variants',
  'evidence.derivedExplanation': 'How this term was formed',
  'evidence.technicalDetails': 'Technical details',
  'evidence.technicalStatus': 'Evidence status',
  'evidence.technicalMethod': 'Translation method',
  'evidence.technicalSourceId': 'Source ID',
  'evidence.technicalRevision': 'Source revision',
  'evidence.technicalRule': 'Composition rule',
  'evidence.technicalBlockers': 'Internal review flags',
  'evidence.technicalClaims': 'Evidence references',
  'evidence.technicalAtlasId': 'Atlas concept ID',
  'evidence.technicalFma': 'FMA ID',
  'evidence.technicalTa2': 'TA2 ID',
  'evidence.technicalBodyParts3d': 'BodyParts3D IDs',
  'detail.originalEnglish': 'Original English term',
  'detail.vietnameseUnavailable': 'Verified Vietnamese terminology not yet available',
  'detail.evidenceSource': 'Evidence source',
  'detail.evidenceReason': 'Reason',
  'detail.evidenceVariants': 'Source variants',
  'detail.evidenceVariantNote': 'Source has variants',
  'detail.generatedNote': 'Temporary translation based on available anatomical terminology; source not identified.',
  'detail.translationMethod': 'Method',
  'detail.canonicalLatin': 'Canonical Latin',
  'detail.sourceIds': 'Source identifiers',
  'detail.atlasReference': 'Atlas reference',
  'detail.selectedPieces': 'Selected pieces',
  'detail.includedStructures': 'Included structures',
  'detail.morePieces': 'And {count} more modeled pieces.',
  'detail.viewSource': 'View anatomical source',
  'detail.showSurrounding': 'Show surrounding anatomy',
  'detail.isolate': 'Isolate structure',
  'detail.clearSelection': 'Clear selection',
  'detail.systemOverview': 'System overview · structure identified from source anatomy',
  'about.eyebrow': 'Source & scope',
  'about.title': 'A body, revealed.',
  'about.description': 'Explore the adult male reference anatomy from BodyParts3D.',
  'about.modelSummary': '{meshes} individual meshes and {concepts} named concepts from an adult male reference anatomy.',
  'about.scope': 'This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.',
  'about.educational': 'Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.',
  'about.modelIdentity': 'Male · BodyParts3D',
  'about.sourceDescription': 'BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.',
  'about.sourceHeading': 'Source',
  'about.datasetLicense': 'Dataset license',
  'about.originalGeometry': 'Original geometry & metadata',
  'about.sourcePublication': 'Read the source publication',
  'errors.webgl': 'This browser could not start the 3D viewer. Please try a browser with WebGL enabled.',
  'errors.atlasLoad': 'The anatomy catalogue could not be loaded.',
  'errors.chunkLoad': 'Could not load the anatomy.',
  'errors.contextLost': 'The 3D session was paused by your device. Reload to continue.',
  'systems.skeletal': 'Skeleton',
  'systems.muscular': 'Muscles',
  'systems.cardiac': 'Heart',
  'systems.sensory': 'Sensory organs',
  'systems.arterial': 'Arteries',
  'systems.venous': 'Veins',
  'systems.nervous': 'Nervous system',
  'systems.respiratory': 'Respiratory',
  'systems.digestive': 'Digestive',
  'systems.urinary': 'Urinary',
  'systems.lymphatic': 'Lymphatic',
  'systems.endocrine': 'Endocrine',
  'systems.reproductive': 'Reproductive',
  'systems.integumentary': 'Body surface',
  'systems.connective': 'Connective tissue',
  'systemDescription.skeletal': 'Bones form the supporting framework of the body, protect organs, and provide attachment points for muscles. Their internal tissue also stores minerals and produces blood cells.',
  'systemDescription.muscular': 'Skeletal muscles generate movement by pulling on their attachments. Together with tendons, they move joints, stabilize posture, and produce heat.',
  'systemDescription.cardiac': 'The heart is a muscular pump with four chambers. Its valves direct blood forward through the pulmonary and systemic circuits.',
  'systemDescription.sensory': 'These structures contribute to special senses, including sight, hearing, and balance. Their specialized tissues detect stimuli and work with the nervous system to convey information.',
  'systemDescription.arterial': 'The heart drives blood through the circulation. Arteries carry blood away from the heart to supply tissues or, in the pulmonary circuit, to the lungs.',
  'systemDescription.venous': 'Veins return blood toward the heart. Superficial and deep networks collect blood from the tissues; the pulmonary veins bring oxygenated blood back from the lungs.',
  'systemDescription.nervous': 'The brain, spinal cord, and peripheral nerves carry and process signals. They support sensation, movement, coordination, and automatic regulation of body functions.',
  'systemDescription.respiratory': 'The airways conduct air to the lungs, where oxygen and carbon dioxide move between air and blood. Breathing depends on pressure changes produced by respiratory muscles.',
  'systemDescription.digestive': 'The digestive tract breaks down food, absorbs nutrients and water, and moves waste onward. Accessory organs contribute bile and digestive enzymes.',
  'systemDescription.urinary': 'The kidneys filter blood and regulate fluid, electrolyte, and acid–base balance. Urine travels through the ureters to the bladder and exits through the urethra.',
  'systemDescription.lymphatic': 'Lymphatic vessels return excess tissue fluid to the circulation. Lymph nodes and other lymphoid organs support immune surveillance and responses.',
  'systemDescription.endocrine': 'Endocrine organs release hormones into the blood to coordinate processes such as metabolism, growth, stress responses, and reproduction.',
  'systemDescription.reproductive': 'The male reproductive structures represented here contribute to sperm production, maturation, transport, and the production of sex hormones.',
  'systemDescription.integumentary': 'The body surface provides an outer anatomical reference. The integumentary system forms a protective barrier and contributes to sensation and temperature regulation.',
  'systemDescription.connective': 'Cartilage, ligaments, and other connective tissues support, connect, and separate structures. Their roles include stabilizing joints and distributing mechanical loads.',
  'structureDescription.heart': 'A muscular pump in the chest. Its right side sends blood to the lungs; its left side sends blood through the systemic circulation.',
  'structureDescription.liver': 'A large organ beneath the right side of the diaphragm. It processes absorbed nutrients, produces bile, and synthesizes many proteins carried in the blood.',
  'structureDescription.brain': 'The central organ of the nervous system. Its interconnected regions support perception, movement, memory, language, and the regulation of bodily functions.',
  'structureDescription.stomach': 'A muscular chamber between the esophagus and small intestine. It stores and mixes food with acid and enzymes before releasing it into the duodenum.',
  'structureDescription.spleen': 'A lymphoid organ in the upper left abdomen. It filters blood, removes aging blood cells, and participates in immune responses.',
  'structureDescription.pancreas': 'An abdominal organ with digestive and endocrine roles. It supplies enzymes to the small intestine and releases hormones including insulin and glucagon.',
  'structureDescription.urinaryBladder': 'A muscular reservoir in the pelvis that stores urine arriving from the kidneys through the ureters.',
  'structureDescription.trachea': 'The main airway connecting the larynx to the bronchi. Its cartilage supports keep the airway open during breathing.',
  'structureDescription.diaphragm': 'A broad muscle separating the chest and abdomen. When it contracts, it increases chest volume and helps draw air into the lungs.',
} as const;

const vietnameseMessages = {
  'language.label': 'Ngôn ngữ',
  'language.english': 'English',
  'language.vietnamese': 'Tiếng Việt',
  'brand.name': 'Human Atlas',
  'brand.interactiveAnatomy': 'Giải phẫu tương tác',
  'identity.modeledPieces': '{count} mảnh mô hình',
  'identity.source': 'BodyParts3D',
  'navigation.explorerPanels': 'Bảng điều khiển khám phá',
  'controls.search': 'Tìm cấu trúc',
  'controls.searchAria': 'Tìm kiếm giải phẫu',
  'controls.about': 'Giới thiệu atlas',
  'controls.closePanel': 'Đóng bảng',
  'controls.systems': 'Các hệ cơ quan',
  'controls.closeSystems': 'Đóng các hệ cơ quan',
  'controls.all': 'Tất cả',
  'controls.skeleton': 'Hệ xương',
  'controls.organs': 'Cơ quan',
  'controls.hideAll': 'Ẩn tất cả',
  'controls.reset': 'Đặt lại',
  'controls.resetViewLayers': 'Đặt lại góc nhìn và các lớp',
  'controls.explode': 'Tách giải phẫu',
  'controls.assembled': 'Lắp ráp',
  'controls.everyPiece': 'Từng mảnh',
  'controls.openSystems': 'Mở các lớp hệ cơ quan',
  'controls.sourceCredits': 'Nguồn & ghi công',
  'controls.showOnlySystem': 'Chỉ hiển thị hệ này',
  'controls.toggleSystem': 'Hiển thị hoặc ẩn hệ này',
  'controls.piecesVisible': '{count} mảnh đang hiển thị',
  'search.close': 'Đóng tìm kiếm',
  'search.dismiss': 'Đóng gợi ý tìm kiếm',
  'search.placeholder': 'Tìm theo tên tiếng Việt, tiếng Anh hoặc mã…',
  'search.aria': 'Tìm kiếm các cấu trúc giải phẫu có tên',
  'search.noMatches': 'Không có cấu trúc phù hợp.',
  'search.emptyHint': 'Bắt đầu với một cơ quan lớn hoặc tìm trong mọi cấu trúc có tên.',
  'search.refineHint': 'Hiển thị tối đa 80 kết quả. Hãy thu hẹp tìm kiếm để tìm cấu trúc nhỏ hơn.',
  'search.piece': 'mảnh',
  'search.pieces': 'mảnh',
  'loading.preparing': 'Đang chuẩn bị dữ liệu giải phẫu',
  'loading.progress': '{progress}% · Đang tải {count} mảnh',
  'controls.reload': 'Tải lại trình xem',
  'camera.controls': 'Điều khiển góc nhìn',
  'camera.threeQuarter': 'Góc nhìn ba phần tư',
  'camera.front': 'Góc nhìn trước',
  'camera.side': 'Góc nhìn bên',
  'camera.back': 'Góc nhìn sau',
  'camera.rotate': 'Xoay mô hình',
  'camera.pause': 'Tạm dừng xoay',
  'camera.autoRotate': 'Tự động xoay',
  'camera.dragOrbit': 'Kéo để xoay quanh',
  'camera.dragPan': 'Kéo để di chuyển',
  'camera.pinchZoom': 'Chụm để thu phóng',
  'camera.tapInspect': 'Chạm để xem chi tiết',
  'scene.aria': 'Giải phẫu người tương tác. Kéo để xoay, chụm hoặc cuộn để thu phóng, chạm vào một cấu trúc để xem chi tiết.',
  'scene.selectedStructure': 'Cấu trúc đang chọn',
  'scene.inventory': 'Danh mục giải phẫu',
  'scene.separatedStructures': 'Cấu trúc đã tách',
  'scene.adultMale': 'NGƯỜI TRƯỞNG THÀNH · NAM',
  'evidence.verified': 'Đã xác minh',
  'evidence.provisionalSourced': 'Chưa xác minh đầy đủ',
  'evidence.provisionalTranslated': 'Chưa xác định nguồn',
  'evidence.noTranslation': 'Chỉ có tiếng Anh',
  'evidence.direct.label': 'Đã xác minh nguồn',
  'evidence.direct.description': 'Thuật ngữ được đối chiếu với tài liệu chuyên ngành.',
  'evidence.multiAuthority.description': 'Thuật ngữ được ghi nhận trong {count} nguồn độc lập.',
  'evidence.derived.label': 'Suy dẫn từ thuật ngữ đã xác minh',
  'evidence.derived.description': 'Thuật ngữ được tạo theo quy tắc nhất quán từ các thành phần đã có nguồn; toàn bộ cụm từ có thể không xuất hiện nguyên văn trong một nguồn.',
  'evidence.sourced.label': 'Có nguồn tham khảo',
  'evidence.sourced.qualifier': 'Chưa xác minh đầy đủ',
  'evidence.sourced.description': 'Có thuật ngữ từ tài liệu tham khảo nhưng còn khác biệt về phạm vi hoặc cách dùng.',
  'evidence.generated.label': 'Bản dịch tạm',
  'evidence.generated.qualifier': 'Chưa xác định nguồn',
  'evidence.generated.description': 'Bản dịch được tạo để hỗ trợ sử dụng tiếng Việt và chưa có nguồn thuật ngữ được xác nhận.',
  'evidence.conflict.label': 'Có biến thể nguồn',
  'evidence.conflict.description': 'Các tài liệu tham khảo sử dụng những cách gọi khác nhau.',
  'evidence.noTranslation.label': 'Chưa có thuật ngữ tiếng Việt',
  'evidence.noTranslation.description': 'Bản ghi thuật ngữ chưa có thuật ngữ tiếng Việt.',
  'evidence.sourceHeading': 'Nguồn',
  'evidence.showSourceDetails': 'Xem chi tiết nguồn',
  'evidence.sourceUnavailable': 'Chưa có thông tin chi tiết về nguồn tham khảo.',
  'evidence.openSource': 'Mở nguồn tham khảo',
  'evidence.moreSources': '+{count} nguồn',
  'evidence.fullTitle': 'Tên đầy đủ',
  'evidence.institution': 'Cơ quan',
  'evidence.authors': 'Tác giả',
  'evidence.year': 'Năm',
  'evidence.edition': 'Ấn bản',
  'evidence.publisher': 'Nhà xuất bản',
  'evidence.locator': 'Vị trí',
  'evidence.page': 'Trang {page}',
  'evidence.section': 'Mục {section}',
  'evidence.moreLocators': '+{count} vị trí khác',
  'evidence.sourceVariants': 'Các cách gọi được ghi nhận',
  'evidence.derivedExplanation': 'Cách hình thành thuật ngữ',
  'evidence.technicalDetails': 'Chi tiết kỹ thuật',
  'evidence.technicalStatus': 'Trạng thái bằng chứng',
  'evidence.technicalMethod': 'Phương pháp dịch',
  'evidence.technicalSourceId': 'Mã nguồn',
  'evidence.technicalRevision': 'Bản sửa đổi nguồn',
  'evidence.technicalRule': 'Mã quy tắc kết hợp',
  'evidence.technicalBlockers': 'Mã rà soát nội bộ',
  'evidence.technicalClaims': 'Mã tham chiếu bằng chứng',
  'evidence.technicalAtlasId': 'Mã khái niệm atlas',
  'evidence.technicalFma': 'Mã FMA',
  'evidence.technicalTa2': 'Mã TA2',
  'evidence.technicalBodyParts3d': 'Mã BodyParts3D',
  'detail.originalEnglish': 'Tên tiếng Anh gốc',
  'detail.vietnameseUnavailable': 'Chưa có thuật ngữ tiếng Việt đã được thẩm định',
  'detail.evidenceSource': 'Nguồn tham khảo',
  'detail.evidenceReason': 'Lý do',
  'detail.evidenceVariants': 'Biến thể nguồn',
  'detail.evidenceVariantNote': 'Có biến thể nguồn',
  'detail.generatedNote': 'Bản dịch tạm dựa trên thuật ngữ giải phẫu hiện có; chưa xác định nguồn cho thuật ngữ này.',
  'detail.translationMethod': 'Phương pháp',
  'detail.canonicalLatin': 'Tên Latin chuẩn',
  'detail.sourceIds': 'Mã định danh nguồn',
  'detail.atlasReference': 'Mã tham chiếu atlas',
  'detail.selectedPieces': 'Mảnh đã chọn',
  'detail.includedStructures': 'Các cấu trúc đi kèm',
  'detail.morePieces': 'Còn {count} mảnh mô hình khác.',
  'detail.viewSource': 'Xem nguồn dữ liệu giải phẫu',
  'detail.showSurrounding': 'Hiển thị vùng xung quanh',
  'detail.isolate': 'Cô lập cấu trúc',
  'detail.clearSelection': 'Bỏ chọn',
  'detail.systemOverview': 'Tổng quan hệ cơ quan · cấu trúc được nhận diện từ giải phẫu nguồn',
  'about.eyebrow': 'Nguồn & phạm vi',
  'about.title': 'Khám phá cơ thể.',
  'about.description': 'Khám phá giải phẫu tham chiếu nam trưởng thành từ BodyParts3D.',
  'about.modelSummary': '{meshes} lưới riêng lẻ và {concepts} khái niệm có tên trong bộ giải phẫu tham chiếu nam trưởng thành.',
  'about.scope': 'Tài liệu tham chiếu này không bao gồm mọi cấu trúc hoặc biến thể của cơ thể người. Một khái niệm có tên có thể gồm nhiều mảnh; mỗi lưới nguồn chỉ được hiển thị một lần.',
  'about.educational': 'Màu sắc và cách nhóm hệ cơ quan phục vụ mục đích khám phá. Hình học được giản lược cho web, còn phần giải thích ngắn chỉ mang tính giáo dục. Đây là tài liệu tham khảo giải phẫu, không phải công cụ chẩn đoán hay phẫu thuật.',
  'about.modelIdentity': 'Nam · BodyParts3D',
  'about.sourceDescription': 'BodyParts3D, © Database Center for Life Science, theo giấy phép CC Attribution 4.0 International.',
  'about.sourceHeading': 'Nguồn',
  'about.datasetLicense': 'Giấy phép dữ liệu',
  'about.originalGeometry': 'Hình học & siêu dữ liệu gốc',
  'about.sourcePublication': 'Đọc ấn phẩm nguồn',
  'errors.webgl': 'Trình duyệt không thể khởi động trình xem 3D. Hãy thử trình duyệt có hỗ trợ WebGL.',
  'errors.atlasLoad': 'Không thể tải danh mục giải phẫu.',
  'errors.chunkLoad': 'Không thể tải dữ liệu giải phẫu.',
  'errors.contextLost': 'Phiên 3D đã bị thiết bị tạm dừng. Hãy tải lại để tiếp tục.',
  'systems.skeletal': 'Hệ xương',
  'systems.muscular': 'Hệ cơ',
  'systems.cardiac': 'Tim',
  'systems.sensory': 'Cơ quan cảm giác',
  'systems.arterial': 'Động mạch',
  'systems.venous': 'Tĩnh mạch',
  'systems.nervous': 'Hệ thần kinh',
  'systems.respiratory': 'Hệ hô hấp',
  'systems.digestive': 'Hệ tiêu hóa',
  'systems.urinary': 'Hệ tiết niệu',
  'systems.lymphatic': 'Hệ bạch huyết',
  'systems.endocrine': 'Hệ nội tiết',
  'systems.reproductive': 'Hệ sinh sản',
  'systems.integumentary': 'Bề mặt cơ thể',
  'systems.connective': 'Mô liên kết',
  'systemDescription.skeletal': 'Xương tạo nên khung nâng đỡ cơ thể, bảo vệ các cơ quan và là nơi bám của cơ. Mô bên trong xương còn dự trữ khoáng chất và tạo tế bào máu.',
  'systemDescription.muscular': 'Cơ vân tạo chuyển động bằng cách kéo vào các điểm bám. Cùng với gân, cơ giúp vận động khớp, giữ tư thế và tạo nhiệt.',
  'systemDescription.cardiac': 'Tim là một máy bơm cơ gồm bốn buồng. Các van hướng dòng máu đi về phía trước qua vòng tuần hoàn phổi và hệ thống.',
  'systemDescription.sensory': 'Các cấu trúc này tham gia vào những giác quan đặc biệt như thị giác, thính giác và thăng bằng. Mô chuyên biệt tiếp nhận kích thích và phối hợp với hệ thần kinh để truyền thông tin.',
  'systemDescription.arterial': 'Tim thúc đẩy máu lưu thông. Động mạch đưa máu rời tim để nuôi mô hoặc, trong vòng tuần hoàn phổi, đưa máu đến phổi.',
  'systemDescription.venous': 'Tĩnh mạch đưa máu trở về tim. Các mạng lưới nông và sâu thu nhận máu từ mô; tĩnh mạch phổi đưa máu giàu oxy từ phổi trở về tim.',
  'systemDescription.nervous': 'Não, tủy sống và các dây thần kinh ngoại biên truyền và xử lý tín hiệu. Chúng hỗ trợ cảm giác, vận động, phối hợp và điều hòa tự động các chức năng cơ thể.',
  'systemDescription.respiratory': 'Đường thở dẫn khí đến phổi, nơi oxy và carbon dioxide trao đổi giữa khí và máu. Hô hấp phụ thuộc vào thay đổi áp suất do cơ hô hấp tạo ra.',
  'systemDescription.digestive': 'Ống tiêu hóa phân giải thức ăn, hấp thu chất dinh dưỡng và nước, rồi đưa chất thải đi tiếp. Các cơ quan phụ trợ cung cấp mật và enzyme tiêu hóa.',
  'systemDescription.urinary': 'Thận lọc máu và điều hòa dịch, điện giải cũng như cân bằng acid–base. Nước tiểu đi qua niệu quản đến bàng quang rồi ra ngoài qua niệu đạo.',
  'systemDescription.lymphatic': 'Mạch bạch huyết đưa lượng dịch mô dư thừa trở lại tuần hoàn. Hạch bạch huyết và các cơ quan lympho khác hỗ trợ giám sát và đáp ứng miễn dịch.',
  'systemDescription.endocrine': 'Các cơ quan nội tiết đưa hormone vào máu để điều phối những quá trình như chuyển hóa, tăng trưởng, đáp ứng stress và sinh sản.',
  'systemDescription.reproductive': 'Các cấu trúc sinh sản nam được thể hiện ở đây góp phần tạo, trưởng thành và vận chuyển tinh trùng cũng như sản xuất hormone sinh dục.',
  'systemDescription.integumentary': 'Bề mặt cơ thể cung cấp một tham chiếu giải phẫu bên ngoài. Hệ da tạo hàng rào bảo vệ và góp phần vào cảm giác, điều hòa nhiệt độ.',
  'systemDescription.connective': 'Sụn, dây chằng và các mô liên kết khác nâng đỡ, nối và phân cách các cấu trúc. Chúng giúp ổn định khớp và phân bố tải cơ học.',
  'structureDescription.heart': 'Một máy bơm cơ ở ngực. Nửa phải đưa máu đến phổi; nửa trái đưa máu vào vòng tuần hoàn hệ thống.',
  'structureDescription.liver': 'Một cơ quan lớn nằm dưới nửa phải cơ hoành. Gan xử lý chất dinh dưỡng đã hấp thu, tạo mật và tổng hợp nhiều protein lưu hành trong máu.',
  'structureDescription.brain': 'Cơ quan trung tâm của hệ thần kinh. Các vùng liên kết của não hỗ trợ nhận thức, vận động, trí nhớ, ngôn ngữ và điều hòa chức năng cơ thể.',
  'structureDescription.stomach': 'Một khoang cơ nằm giữa thực quản và ruột non. Dạ dày chứa và trộn thức ăn với acid, enzyme trước khi đưa xuống tá tràng.',
  'structureDescription.spleen': 'Một cơ quan lympho ở phần trên bên trái ổ bụng. Lách lọc máu, loại bỏ tế bào máu già và tham gia đáp ứng miễn dịch.',
  'structureDescription.pancreas': 'Một cơ quan trong ổ bụng có vai trò tiêu hóa và nội tiết. Tụy đưa enzyme vào ruột non và tiết các hormone như insulin, glucagon.',
  'structureDescription.urinaryBladder': 'Một túi cơ trong chậu hông, chứa nước tiểu từ thận đi xuống qua niệu quản.',
  'structureDescription.trachea': 'Đường thở chính nối thanh quản với phế quản. Các vòng sụn giúp đường thở luôn mở khi hô hấp.',
  'structureDescription.diaphragm': 'Một cơ rộng ngăn cách ngực và bụng. Khi co, cơ hoành làm tăng thể tích lồng ngực và giúp hút khí vào phổi.',
} satisfies Record<keyof typeof englishMessages, string>;

const messages = {en: englishMessages, vi: vietnameseMessages};
export type MessageKey = keyof typeof englishMessages;
export type MessageValues = Record<string, number | string>;
export const MESSAGE_KEYS = Object.keys(englishMessages) as MessageKey[];

export const SYSTEM_MESSAGE_KEYS: Readonly<Record<string, {name: MessageKey; description: MessageKey}>> = {
  skeletal: {name: 'systems.skeletal', description: 'systemDescription.skeletal'},
  muscular: {name: 'systems.muscular', description: 'systemDescription.muscular'},
  cardiac: {name: 'systems.cardiac', description: 'systemDescription.cardiac'},
  sensory: {name: 'systems.sensory', description: 'systemDescription.sensory'},
  arterial: {name: 'systems.arterial', description: 'systemDescription.arterial'},
  venous: {name: 'systems.venous', description: 'systemDescription.venous'},
  nervous: {name: 'systems.nervous', description: 'systemDescription.nervous'},
  respiratory: {name: 'systems.respiratory', description: 'systemDescription.respiratory'},
  digestive: {name: 'systems.digestive', description: 'systemDescription.digestive'},
  urinary: {name: 'systems.urinary', description: 'systemDescription.urinary'},
  lymphatic: {name: 'systems.lymphatic', description: 'systemDescription.lymphatic'},
  endocrine: {name: 'systems.endocrine', description: 'systemDescription.endocrine'},
  reproductive: {name: 'systems.reproductive', description: 'systemDescription.reproductive'},
  integumentary: {name: 'systems.integumentary', description: 'systemDescription.integumentary'},
  connective: {name: 'systems.connective', description: 'systemDescription.connective'},
};

export const STRUCTURE_DESCRIPTION_KEYS: Readonly<Record<string, MessageKey>> = {
  heart: 'structureDescription.heart',
  liver: 'structureDescription.liver',
  brain: 'structureDescription.brain',
  stomach: 'structureDescription.stomach',
  spleen: 'structureDescription.spleen',
  pancreas: 'structureDescription.pancreas',
  'urinary bladder': 'structureDescription.urinaryBladder',
  trachea: 'structureDescription.trachea',
  diaphragm: 'structureDescription.diaphragm',
};

export function isLanguage(value: unknown): value is Language {
  return value === 'en' || value === 'vi';
}

export function translate(language: Language, key: MessageKey, values?: MessageValues): string {
  let message = messages[language][key] ?? messages.en[key] ?? key;
  for (const [name, value] of Object.entries(values ?? {})) message = message.replaceAll(`{${name}}`, String(value));
  return message;
}

export const getMessage = translate;

type StorageReader = Pick<Storage, 'getItem'>;
type StorageWriter = Pick<Storage, 'setItem'>;

function browserStorage(): (StorageReader & StorageWriter) | undefined {
  if (typeof window === 'undefined') return undefined;
  try {
    return window.localStorage;
  } catch {
    return undefined;
  }
}

export function readStoredLanguage(storage: StorageReader | undefined = browserStorage()): Language {
  try {
    const value = storage?.getItem(LANGUAGE_STORAGE_KEY);
    return isLanguage(value) ? value : DEFAULT_LANGUAGE;
  } catch {
    return DEFAULT_LANGUAGE;
  }
}

export function persistLanguage(language: Language, storage: StorageWriter | undefined = browserStorage()): void {
  try {
    storage?.setItem(LANGUAGE_STORAGE_KEY, language);
  } catch {
    // A blocked or unavailable storage should not prevent the viewer from working.
  }
}
